'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { useApp } from '@/context/AppContext'
import { Download, Check, RefreshCw, Heart, Share2, Palette } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { NavigationHeader } from '@/components/navigation-header'
import { Separator } from '@/components/ui/separator'
import Confetti from 'react-confetti'

function PreviewPage() {
  const router = useRouter()
  const { state, dispatch } = useApp()
  const [downloadStarted, setDownloadStarted] = useState(false)
  const [showSuccessScreen, setShowSuccessScreen] = useState(false)
  const [isLiked, setIsLiked] = useState(false)

  const getColorData = () => {
    const colors = [
      { id: 'white', name: 'White', bgClass: 'bg-white', textClass: 'text-gray-900' },
      { id: 'black', name: 'Black', bgClass: 'bg-black', textClass: 'text-white' },
      { id: 'navy', name: 'Navy', bgClass: 'bg-blue-900', textClass: 'text-white' },
      { id: 'gray', name: 'Gray', bgClass: 'bg-gray-500', textClass: 'text-white' },
      { id: 'red', name: 'Red', bgClass: 'bg-red-500', textClass: 'text-white' },
      { id: 'blue', name: 'Blue', bgClass: 'bg-blue-500', textClass: 'text-white' },
      { id: 'green', name: 'Green', bgClass: 'bg-green-500', textClass: 'text-white' },
    ]
    return colors.find(c => c.id === state.color) || colors[0]
  }


  const downloadImage = async (imageUrl: string, filename: string) => {
    try {
      // For local images (generated by our API)
      if (imageUrl.startsWith('/generated/')) {
        const link = document.createElement('a')
        link.href = imageUrl
        link.download = filename
        document.body.appendChild(link)
        link.click()
        document.body.removeChild(link)
        return
      }
      
      // For remote images (like placeholder images), we need to fetch and convert
      const response = await fetch(imageUrl)
      const blob = await response.blob()
      const url = window.URL.createObjectURL(blob)
      
      const link = document.createElement('a')
      link.href = url
      link.download = filename
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      
      // Clean up the object URL
      window.URL.revokeObjectURL(url)
    } catch (error) {
      console.error('Download failed:', error)
      // Fallback: open in new tab
      window.open(imageUrl, '_blank')
    }
  }

  const handleDownload = async () => {
    if (!state.design?.imageUrl) return
    
    setDownloadStarted(true)
    
    const filename = `shirty-ai-design-${state.productType}-${state.color}-${Date.now()}.png`
    await downloadImage(state.design.imageUrl, filename)
    
    // Show success screen after a brief moment
    setTimeout(() => {
      setShowSuccessScreen(true)
    }, 1000)
  }

  const handleImageDownload = async () => {
    if (!state.design?.imageUrl) return
    
    const filename = `shirty-ai-design-${Date.now()}.png`
    await downloadImage(state.design.imageUrl, filename)
  }

  const handleNewDesign = () => {
    dispatch({ type: 'RESET' })
    router.push('/')
  }

  useEffect(() => {
    if (!state.category || !state.productType || !state.design || !state.color) {
      router.push('/')
    }
  }, [state.category, state.productType, state.design, state.color, router])

  if (!state.category || !state.productType || !state.design || !state.color) {
    return null
  }

  const selectedColorData = getColorData()

  // Success Screen Component
  const SuccessScreen = () => (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 via-pink-50 to-yellow-50 flex items-center justify-center relative overflow-hidden">
      {/* React Confetti */}
      <Confetti
        width={window.innerWidth}
        height={window.innerHeight}
        recycle={false}
        numberOfPieces={300}
        gravity={0.3}
        colors={['#ff6b6b', '#4ecdc4', '#45b7d1', '#96ceb4', '#ffeaa7', '#dda0dd', '#ff7675']}
      />
      
      {/* Celebration Background Elements */}
      <div className="absolute inset-0 pointer-events-none">
        {/* Floating Emoji */}
        <div className="absolute top-10 left-10 text-4xl animate-bounce delay-100">🎉</div>
        <div className="absolute top-20 right-20 text-3xl animate-pulse delay-300">✨</div>
        <div className="absolute top-32 left-1/4 text-2xl animate-bounce delay-500">🎊</div>
        <div className="absolute bottom-32 right-1/3 text-3xl animate-pulse delay-700">🌟</div>
        <div className="absolute top-1/3 right-10 text-2xl animate-bounce delay-900">🎈</div>
        <div className="absolute bottom-20 left-16 text-4xl animate-pulse delay-1100">🎆</div>
        <div className="absolute top-16 left-1/2 transform -translate-x-1/2 text-3xl animate-bounce delay-200">🎨</div>
        <div className="absolute bottom-40 left-20 text-2xl animate-pulse delay-600">🏆</div>
        <div className="absolute top-40 right-16 text-3xl animate-bounce delay-800">🥳</div>
        
        {/* Animated Gradient Orbs */}
        <div className="absolute top-1/4 left-1/4 w-20 h-20 bg-gradient-to-r from-pink-400 to-purple-500 rounded-full opacity-30 animate-pulse"></div>
        <div className="absolute bottom-1/3 right-1/4 w-16 h-16 bg-gradient-to-r from-yellow-400 to-orange-500 rounded-full opacity-40 animate-bounce"></div>
        <div className="absolute top-1/2 left-10 w-12 h-12 bg-gradient-to-r from-green-400 to-blue-500 rounded-full opacity-35 animate-spin"></div>
      </div>

      <div className="max-w-lg mx-auto text-center space-y-8 p-8 relative z-10">
        <div className="space-y-6">
          {/* Celebration Header */}
          <div className="space-y-4">
            <div className="mx-auto w-28 h-28 bg-gradient-to-br from-green-400 via-green-500 to-green-600 rounded-full flex items-center justify-center shadow-2xl animate-pulse">
              <Check className="w-14 h-14 text-white drop-shadow-lg" />
            </div>
            
            <div className="space-y-3">
              <h1 className="text-4xl font-bold bg-gradient-to-r from-purple-600 via-pink-600 to-orange-500 bg-clip-text text-transparent animate-pulse">
                🎉 Woohoo! Download Complete! 🎉
              </h1>
              <p className="text-lg text-gray-700 font-medium">
                Your amazing custom design is ready! Time for some celebration! 🎉✨
              </p>
            </div>
          </div>
          
          {/* Enhanced Design Details Card */}
          <div className="bg-white/80 backdrop-blur-sm rounded-2xl p-6 border-2 border-purple-200 shadow-xl space-y-4">
            <div className="flex items-center justify-center gap-2 mb-4">
              <span className="text-2xl">🎨</span>
              <h3 className="font-bold text-xl text-gray-800">Your Masterpiece Details</h3>
              <span className="text-2xl">🎨</span>
            </div>
            
            <div className="grid grid-cols-2 gap-4">
              <div className="bg-gradient-to-br from-blue-50 to-purple-50 rounded-lg p-3 border border-blue-200">
                <div className="text-xs font-semibold text-blue-600 uppercase tracking-wide">Product</div>
                <div className="text-sm font-bold text-gray-800 mt-1">
                  {state.productType === 'tshirt' ? '👕 T-Shirt' : state.productType === 'hoodie' ? '🧥 Hoodie' : '🥽 Sweatshirt'}
                </div>
              </div>
              
              <div className="bg-gradient-to-br from-pink-50 to-red-50 rounded-lg p-3 border border-pink-200">
                <div className="text-xs font-semibold text-pink-600 uppercase tracking-wide">Color</div>
                <div className="text-sm font-bold text-gray-800 mt-1 flex items-center gap-2">
                  <div className={`w-3 h-3 rounded-full ${selectedColorData?.bgClass} border border-gray-300`}></div>
                  {selectedColorData?.name}
                </div>
              </div>
              
              <div className="bg-gradient-to-br from-green-50 to-teal-50 rounded-lg p-3 border border-green-200">
                <div className="text-xs font-semibold text-green-600 uppercase tracking-wide">Style</div>
                <div className="text-sm font-bold text-gray-800 mt-1 capitalize">{state.design?.style}</div>
              </div>
              
              <div className="bg-gradient-to-br from-yellow-50 to-orange-50 rounded-lg p-3 border border-yellow-200">
                <div className="text-xs font-semibold text-orange-600 uppercase tracking-wide">Category</div>
                <div className="text-sm font-bold text-gray-800 mt-1 capitalize">{state.category}</div>
              </div>
            </div>
          </div>

          {/* Fun Stats */}
          <div className="bg-gradient-to-r from-purple-100/50 to-pink-100/50 rounded-xl p-4 border border-purple-200">
            <div className="grid grid-cols-3 gap-4 text-center">
              <div>
                <div className="text-2xl animate-bounce">⚡</div>
                <div className="text-xs font-semibold text-purple-600">AI Generated</div>
              </div>
              <div>
                <div className="text-2xl animate-pulse">🎯</div>
                <div className="text-xs font-semibold text-pink-600">100% Unique</div>
              </div>
              <div>
                <div className="text-2xl animate-spin">🌟</div>
                <div className="text-xs font-semibold text-orange-600">Ready to Wear</div>
              </div>
            </div>
          </div>
          
          {/* Enhanced Action Buttons */}
          <div className="space-y-4">
            <Button
              onClick={handleNewDesign}
              size="lg"
              className="w-full h-14 text-lg bg-gradient-to-r from-purple-600 via-pink-600 to-purple-600 hover:from-purple-700 hover:via-pink-700 hover:to-purple-700 text-white font-bold rounded-xl shadow-lg transform hover:scale-105 transition-all duration-200"
            >
              <span className="mr-2">🎨</span>
              Create Another Masterpiece
              <span className="ml-2">✨</span>
            </Button>
            
            <div className="grid grid-cols-2 gap-3">
              <Button
                onClick={() => router.push('/')}
                variant="outline"
                size="lg"
                className="h-12 border-2 border-purple-300 hover:border-purple-500 hover:bg-purple-50 font-semibold rounded-xl transform hover:scale-105 transition-all duration-200"
              >
                🏠 Home
              </Button>
              <Button
                onClick={() => router.push('/design')}
                variant="outline"
                size="lg"
                className="h-12 border-2 border-pink-300 hover:border-pink-500 hover:bg-pink-50 font-semibold rounded-xl transform hover:scale-105 transition-all duration-200"
              >
                🔄 Redesign
              </Button>
            </div>
          </div>

          {/* Celebration Message */}
          <div className="bg-gradient-to-r from-green-100 to-blue-100 border-2 border-green-300 rounded-xl p-4">
            <p className="text-lg font-bold text-green-800 animate-bounce">
              🎉 Congratulations! Your design is absolutely amazing! 🎨
            </p>
          </div>
        </div>
      </div>

      {/* Additional floating animations */}
      <style jsx>{`
        @keyframes float {
          0%, 100% { transform: translateY(0px) rotate(0deg); }
          50% { transform: translateY(-20px) rotate(180deg); }
        }
        
        @keyframes sparkle {
          0%, 100% { opacity: 1; transform: scale(1); }
          50% { opacity: 0.5; transform: scale(1.2); }
        }
        
        .animate-float {
          animation: float 3s ease-in-out infinite;
        }
        
        .animate-sparkle {
          animation: sparkle 2s ease-in-out infinite;
        }
      `}</style>
    </div>
  )

  // Show success screen if order is placed
  if (showSuccessScreen) {
    return <SuccessScreen />
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-background to-accent/5">
      <NavigationHeader 
        title="Your Custom Design"
        subtitle="Preview your custom design and add it to cart"
        currentStep={4}
        totalSteps={4}
        showCart={true}
      />

      <div className="max-w-7xl mx-auto px-4 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
          {/* Left Column - Product Preview */}
          <div className="space-y-6">
            <Card className="border-2">
              <CardHeader className="pb-4">
                <div className="flex items-center justify-between">
                  <CardTitle className="flex items-center gap-2">
                    <Palette className="w-5 h-5 text-purple-500" />
                    Product Preview
                  </CardTitle>
                  <div className="flex gap-2">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => setIsLiked(!isLiked)}
                      className="h-9 w-9 p-0"
                    >
                      <Heart 
                        className={`w-4 h-4 ${isLiked ? 'fill-red-500 text-red-500' : ''}`} 
                      />
                    </Button>
                    <Button variant="outline" size="sm" className="h-9 w-9 p-0">
                      <Share2 className="w-4 h-4" />
                    </Button>
                    <Button 
                      variant="outline" 
                      size="sm" 
                      className="h-9 w-9 p-0"
                      onClick={handleImageDownload}
                      title="Download Image"
                    >
                      <Download className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent className="space-y-6">
                {/* Main Product View */}
                <div className="relative">
                  <div 
                    className={`aspect-square rounded-2xl ${selectedColorData?.bgClass} border-4 border-border/50 flex items-center justify-center relative overflow-hidden shadow-2xl transition-all duration-500`}
                  >
                    {state.design.imageUrl ? (
                      <img 
                        src={state.design.imageUrl} 
                        alt="Generated design"
                        className="w-4/5 h-4/5 object-contain rounded-lg drop-shadow-lg"
                      />
                    ) : (
                      <div className={`text-center p-8 ${selectedColorData?.textClass}`}>
                        <div className="text-8xl mb-6 animate-pulse">🎨</div>
                        <p className="font-bold text-lg mb-2">AI Generated Design</p>
                        <p className="text-sm opacity-80 max-w-xs">"{state.design.prompt}"</p>
                        <Badge variant="secondary" className="mt-4">
                          {state.design.style} Style
                        </Badge>
                      </div>
                    )}
                    
                    {/* Product Label */}
                    <div className="absolute top-4 left-4">
                      <Badge className="bg-background/90 text-foreground border">
                        {state.productType === 'tshirt' ? '👕 T-Shirt' : state.productType === 'hoodie' ? '🧥 Hoodie' : '🥽 Sweatshirt'}
                      </Badge>
                    </div>
                  </div>
                  
                  {/* Product Info Bar */}
                  <div className="mt-6 p-4 bg-accent/30 rounded-xl">
                    <div className="flex items-center justify-between">
                      <div>
                        <h3 className="font-poppins font-bold text-lg">
                          Custom {state.productType === 'tshirt' ? 'T-Shirt' : state.productType === 'hoodie' ? 'Hoodie' : 'Sweatshirt'}
                        </h3>
                        <p className="text-sm text-muted-foreground">
                          {selectedColorData?.name} • {state.design.style} Style • {state.category}
                        </p>
                      </div>
                      <div className="text-right">
                        <div className="text-lg font-bold text-primary">Ready to Order</div>
                        <div className="text-xs text-muted-foreground">Premium Quality</div>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Selected Color Display */}
                <div>
                  <div className="flex items-center justify-between mb-4">
                    <h4 className="font-poppins font-semibold flex items-center gap-2">
                      <div className="w-2 h-2 rounded-full bg-primary"></div>
                      Product Color
                    </h4>
                    <Badge variant="outline">Selected in Design</Badge>
                  </div>
                  
                  <div className="flex items-center gap-4 p-3 bg-accent/30 rounded-lg">
                    <div 
                      className={`w-12 h-12 rounded-full ${selectedColorData?.bgClass} border-4 border-primary/20 shadow-lg`}
                    ></div>
                    <div>
                      <div className="font-medium">{selectedColorData?.name}</div>
                      <div className="text-sm text-muted-foreground">Color chosen during design</div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Right Column - Details & Actions */}
          <div className="space-y-6">
            {/* Design Details */}
            <Card className="border-2">
              <CardHeader>
                <CardTitle>Design Details</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-4">
                  <div className="flex justify-between items-center p-3 bg-accent/30 rounded-lg">
                    <span className="text-muted-foreground font-medium">Art Style:</span>
                    <Badge variant="secondary" className="capitalize text-sm px-3 py-1">
                      {state.design.style}
                    </Badge>
                  </div>
                  
                  <div className="p-3 bg-accent/30 rounded-lg">
                    <div className="text-muted-foreground font-medium mb-2">Design Prompt:</div>
                    <p className="text-sm italic bg-background/50 p-3 rounded border-l-4 border-primary">
                      "{state.design.prompt}"
                    </p>
                  </div>
                  
                  <div className="flex justify-between items-center p-3 bg-accent/30 rounded-lg">
                    <span className="text-muted-foreground font-medium">Category:</span>
                    <Badge variant="outline" className="capitalize">
                      {state.category}
                    </Badge>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Product Info */}
            <Card className="border-2 bg-gradient-to-r from-primary/5 to-primary/10">
              <CardContent className="pt-6">
                <div className="space-y-4">
                  <div className="text-center">
                    <h3 className="text-xl font-bold text-primary mb-2">Your Custom Design</h3>
                    <p className="text-muted-foreground">Ready to add to your collection</p>
                  </div>
                  
                  <Separator />
                  
                  <div className="grid grid-cols-2 gap-4 text-center text-sm">
                    <div>
                      <div className="text-lg">⭐</div>
                      <div className="text-muted-foreground">Premium Quality</div>
                    </div>
                    <div>
                      <div className="text-lg">🎨</div>
                      <div className="text-muted-foreground">AI Generated</div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Action Buttons */}
            <div className="space-y-4">
              <Button
                onClick={handleDownload}
                disabled={downloadStarted}
                size="lg"
                className={`w-full h-14 text-lg ${
                  downloadStarted ? 'bg-green-600 hover:bg-green-700' : ''
                }`}
              >
                {downloadStarted ? (
                  <>
                    <Check className="mr-3" size={24} />
                    Downloading...
                  </>
                ) : (
                  <>
                    <Download className="mr-3" size={24} />
                    Download Final Image
                  </>
                )}
              </Button>

              <div className="grid grid-cols-2 gap-4">
                <Button
                  onClick={handleNewDesign}
                  variant="outline"
                  size="lg"
                  className="h-12"
                >
                  <RefreshCw className="mr-2" size={18} />
                  New Design
                </Button>
                
                <Button
                  onClick={() => router.push('/design')}
                  variant="outline"
                  size="lg"
                  className="h-12"
                >
                  <Palette className="mr-2" size={18} />
                  Edit Design
                </Button>
              </div>
            </div>

            {/* Trust Indicators */}
            <Card>
              <CardContent className="pt-6">
                <div className="grid grid-cols-3 gap-4 text-center">
                  <div>
                    <div className="text-2xl mb-1">⭐</div>
                    <div className="text-xs text-muted-foreground">4.9/5 Rating</div>
                  </div>
                  <div>
                    <div className="text-2xl mb-1">🚚</div>
                    <div className="text-xs text-muted-foreground">Free Shipping</div>
                  </div>
                  <div>
                    <div className="text-2xl mb-1">🔒</div>
                    <div className="text-xs text-muted-foreground">Secure Payment</div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  )
}

export default function Preview() {
  return <PreviewPage />
}